### ISSUE TITLE
locking

### ISSUE THREAD

**Issue by bmeck** [jhusain/compositional-functions#1]
in general I would expect there to be some form of locking to prevent multiple continuations from occuring on the generator inside of our compositional function. this means that when our runner gets the generator it cannot call next without await being active, and it needs a token of some kind to continue the function (that can only be used once).

**Comment by jhusain** [comment]
Can you be more specific about the problem you're trying to solve?

**Comment by bmeck** [comment]
During composition, the async controller is given a generator function to execute. This is a bit troublesome if we want to guarantee in order execution. Take a look at the following:

``` javascript
function* out_of_order(oob_ctrlF) {
   let oob_ctrl =oob_ctrlF();
   setTimeout(()=> {
    oob_ctrl.next();
   }, 0)
   // await our fetch result
   yield fetch(url);
}
function async(genF) {
  let gen;
  // means to give oob control to our generator
   function oob_ctrlF() {
     return gen;
   }
  gen = genF(oob_stepper);
  // all the normal
}
```

if you take a look at `out_of_order` you will notice that there is no check that we are finishing the result of `fetch` with the current proposal, so the timeout will continue the generator. This also would mean that programmers will be unable to assume that async functions are guaranteed to be executed "in order".

I looked at several ways to fix this in [generator-runner](https://github.com/bmeck/generator-runner), but ended up using locks as the only way to enforce this guarantee.

**Comment by nmn** [comment]
I don't see this as a problem. The main point of the proposal is to provide some synctactic sugar. Anything you can do with compositional functions, you can pretty much do with just a generator function and a helper function. (Things do a get a little hairy with `yeild

So the fact is that if you make a function that passes control of execution to a generator function yourself, that's on you. It won't run in order, but we should assume you wanted to do that. And, in fact, this could actually be useful in some cases.

**Comment by bmeck** [comment]
if we want to leave it to the runners that is fine, but it is a concern
that I would at least like to be noted somewhere.

**Comment by benjamingr** [comment]
I'm also in favour of this being solved in runner level.

**Comment by nmn** [comment]
Same here. This is simple synctactic sugar around generator functions anyway. I see no reason, why it should try to solve locking.
