### ISSUE TITLE
out of band cancellation

### ISSUE THREAD

**Issue by bmeck** [jhusain/compositional-functions#2]
This is a very important note in allowing resource guards. Out of band cancellation allows for resources to affect the cancellation of a task. I have talked about this some in: https://github.com/tc39/ecmascript-asyncawait/issues/27 . However, I will rephrase it here. The easiest example is lock files; given the following:

``` javascript
async function () {
  try {
    let lock = await getLock(__filename);
    lock.oncompromised = cancel;
    // tasks requiring the lock
  }
  finally {
    // cleanup
  }
}
```

It is important to allow the lock to cancel any tasks requiring it. By cancel I do not mean to rollback, but rather to stop execution of the next task and instead attempt to return (not throw). The alternative is to force every await to have a programmatic guard which is more error prone and requires knowledge of how to check if a resource is compromised.

**Comment by bmeck** [comment]
@jhusain if this is purely a syntactic sugar as #1 implies, we can close this is issue. However, once again I would like to strongly note that cancellation and resource cleanup should not be an afterthought though. The current Promise based runner from async functions is somewhat painful in both these regards.

**Comment by jhusain** [comment]
We are definitely considering this carefully. The point is that the syntax is merely about composition, and is up to the type itself to provide cancellation semantics. There are many different ways of doing this.
